import { Recipe } from "./types"

export const MOCK_RECIPES: Recipe[] = [
  {
    id: "1",
    title: "Street Tacos",
    description: "Classic beef tacos with fresh cilantro and onions.",
    image: "/delicious-tacos.png",
    prepTime: 20,
    tags: ["Mexican", "Quick"],
    ingredients: [
      { name: "Corn Tortillas", amount: 6, unit: "pcs", category: "Grains" },
      { name: "Ground Beef", amount: 1, unit: "lb", category: "Protein" },
      { name: "White Onion", amount: 0.5, unit: "whole", category: "Produce" },
      { name: "Cilantro", amount: 1, unit: "bunch", category: "Produce" },
      { name: "Lime", amount: 2, unit: "whole", category: "Produce" },
    ],
  },
  {
    id: "2",
    title: "Loaded Burritos",
    description: "Hearty burritos with rice, beans, and cheese.",
    image: "/delicious-burrito.png",
    prepTime: 30,
    tags: ["Mexican", "Hearty"],
    ingredients: [
      { name: "Flour Tortillas", amount: 4, unit: "pcs", category: "Grains" },
      { name: "Ground Beef", amount: 0.5, unit: "lb", category: "Protein" },
      { name: "Black Beans", amount: 1, unit: "can", category: "Pantry" },
      { name: "Rice", amount: 1, unit: "cup", category: "Pantry" },
      { name: "Cheddar Cheese", amount: 1, unit: "cup", category: "Dairy" },
      { name: "Sour Cream", amount: 0.5, unit: "cup", category: "Dairy" },
    ],
  },
  {
    id: "3",
    title: "Cheese Quesadillas",
    description: "Simple and crispy cheese quesadillas.",
    image: "/cheesy-quesadilla.png",
    prepTime: 15,
    tags: ["Mexican", "Vegetarian"],
    ingredients: [
      { name: "Flour Tortillas", amount: 2, unit: "pcs", category: "Grains" },
      { name: "Cheddar Cheese", amount: 1, unit: "cup", category: "Dairy" },
      { name: "Salsa", amount: 0.5, unit: "cup", category: "Pantry" },
    ],
  },
  {
    id: "4",
    title: "Greek Salad",
    description: "Fresh salad with feta, olives, and cucumbers.",
    image: "/greek-salad.jpg",
    prepTime: 15,
    tags: ["Mediterranean", "Healthy"],
    ingredients: [
      { name: "Cucumber", amount: 1, unit: "whole", category: "Produce" },
      { name: "Tomatoes", amount: 2, unit: "whole", category: "Produce" },
      { name: "Red Onion", amount: 0.5, unit: "whole", category: "Produce" },
      { name: "Feta Cheese", amount: 0.5, unit: "cup", category: "Dairy" },
      { name: "Kalamata Olives", amount: 0.5, unit: "cup", category: "Pantry" },
      { name: "Olive Oil", amount: 2, unit: "tbsp", category: "Pantry" },
    ],
  },
  {
    id: "5",
    title: "Chicken Stir Fry",
    description: "Vegetable packed stir fry with soy sauce glaze.",
    image: "/vibrant-vegetable-stir-fry.png",
    prepTime: 25,
    tags: ["Asian", "Healthy"],
    ingredients: [
      { name: "Chicken Breast", amount: 1, unit: "lb", category: "Protein" },
      { name: "Broccoli", amount: 1, unit: "head", category: "Produce" },
      { name: "Carrots", amount: 2, unit: "whole", category: "Produce" },
      { name: "Soy Sauce", amount: 0.25, unit: "cup", category: "Pantry" },
      { name: "Rice", amount: 1, unit: "cup", category: "Pantry" },
      { name: "Ginger", amount: 1, unit: "inch", category: "Produce" },
    ],
  },
]
